server:
  port: 8091
spring:
  application:
    name: jenkins-server
  zipkin:
    base-url: http://192.168.101.98:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.101.98:9001/eureka/
    fetch-registry:
      true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

swagger2.package: com.cloudzone.jenkins.service

jenkins:
  host: 192.168.101.90
  port: 8089
  username: zhoufei17
  password: Abcd123

api:
  version: 1.0
  name: jenkins-server

job.config.path: templates/jobConfig.xml

console.server.url: 192.168.101.98:9999